[config]
# will be set to mainnet by default if omitted
# rpc = "https://fullnode.testnet.sui.io:443"

[packages]
AnimaLib = { local = "../../../packages/AnimaLib" }
Anima = { local = "../../../packages/Anima" }
ACT = { local = "../../../packages/ACT" }